"""Design-token exports: CSS custom properties, flat JSON, the W3C design-tokens format, and the full catalog."""

from __future__ import annotations

import json
from pathlib import Path

from .. import colormath as C
from ..catalog import Catalog, load


def _write(path, text: str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def _css_name(token: str) -> str:
    return "--ulg-" + token.replace(".", "-").replace("_", "-")


def css(path=None, *, catalog: Catalog | None = None, selector: str = ":root") -> str:
    """CSS custom properties: ``--ulg-grass-300`` for palette colours, ``--ulg-lawn-fill`` etc. for elements."""
    catalog = catalog or load()
    flat = catalog.palette.flat()
    by_hex = {v: k for k, v in reversed(list(flat.items()))}
    lines = [f"/* {catalog.palette.name} - generated by ulg, do not edit */", f"{selector} {{", "  /* palette */"]
    lines += [f"  {_css_name(tok)}: {hexc};" for tok, hexc in flat.items()]
    lines.append("  /* elements */")
    for el in catalog:
        for role, value in (("fill", el.fill), ("outline", el.outline), ("ink", el.ink)):
            if value:
                ref = f"var({_css_name(by_hex[value])})" if value in by_hex else value
                lines.append(f"  {_css_name(el.id)}-{role}: {ref};")
    lines.append("}")
    text = "\n".join(lines) + "\n"
    if path:
        _write(path, text)
    return text


def tokens_json(path=None, *, catalog: Catalog | None = None) -> dict:
    """Flat, tool-agnostic JSON: palette tokens and the resolved colours of every element."""
    catalog = catalog or load()
    data = {
        "name": catalog.palette.name,
        "palette": catalog.palette.flat(),
        "elements": {el.id: {k: v for k, v in (("fill", el.fill), ("outline", el.outline), ("ink", el.ink)) if v}
                     for el in catalog},
    }
    if path:
        _write(path, json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    return data


def _dtcg_color(hexc: str) -> dict:
    r, g, b = C.parse(hexc)
    return {"colorSpace": "srgb", "components": [round(r, 4), round(g, 4), round(b, 4)], "alpha": 1,
            "hex": hexc.lower()}


def dtcg(path=None, *, catalog: Catalog | None = None) -> dict:
    """Design Tokens Community Group format (``.tokens.json``): primitives plus element aliases.

    Reads into Style Dictionary, Tokens Studio, Figma variables importers and
    similar tools. Element colours are aliases (``{palette.grass.300}``) so a
    palette change propagates.
    """
    catalog = catalog or load()
    flat = catalog.palette.flat()
    by_hex = {v: k for k, v in reversed(list(flat.items()))}
    palette: dict = {"$type": "color"}
    for fam, steps in catalog.palette.families.items():
        palette[fam] = {step: {"$value": _dtcg_color(hexc)} for step, hexc in steps.items()}
    elements: dict = {"$type": "color"}
    for el in catalog:
        node = {"$description": el.name("en")}
        for role, value in (("fill", el.fill), ("outline", el.outline), ("ink", el.ink)):
            if value:
                node[role] = {"$value": "{palette." + by_hex[value] + "}" if value in by_hex else _dtcg_color(value)}
        elements[el.id] = node
    data = {"$description": catalog.palette.name, "palette": palette, "element": elements}
    if path:
        _write(path, json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    return data


def catalog_json(path=None, *, catalog: Catalog | None = None) -> dict:
    """The complete resolved catalog in one file: the contract for non-Python apps and AI agents."""
    from .. import __version__

    catalog = catalog or load()
    data = {
        "name": catalog.palette.name,
        "version": __version__,
        "palette": catalog.palette.flat(),
        "elements": {el.id: el.to_dict() for el in catalog},
        "schemes": {name: {k: v for k, v in cw.items() if k != "entries"} | {"entries": cw.get("entries", [])}
                    for name, cw in catalog.crosswalks.items()},
    }
    if path:
        _write(path, json.dumps(data, indent=1, ensure_ascii=False) + "\n")
    return data
