"""Regenerate the reference pages in docs/reference from the catalog and the code.

    python tools/build_reference.py

Writes element-list.md, attributes.md, crosswalks.md, themes.md and api.md.
Never edit those files by hand: change the data or the docstrings and run this.
"""

from __future__ import annotations

import inspect
import io
import sys
from contextlib import redirect_stdout
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import ulg  # noqa: E402
from ulg import check, cli, crosswalk, datasets  # noqa: E402
from ulg.export import qgis, sld, tokens, web  # noqa: E402

REF = ROOT / "docs" / "reference"
HEAD = "<!-- generated by tools/build_reference.py - do not edit by hand -->\n"


def cell(v) -> str:
    return str(v).replace("|", "\\|").replace("\n", " ")


def write(name: str, text: str) -> None:
    REF.mkdir(parents=True, exist_ok=True)
    (REF / name).write_text(HEAD + text.rstrip() + "\n", encoding="utf-8")
    print("  ", (REF / name).relative_to(ROOT))


def by_group(catalog):
    groups: dict[str, list] = {}
    for el in catalog:
        groups.setdefault(el.group, []).append(el)
    return groups


# --------------------------------------------------------------------------- pages

def element_list() -> None:
    cat = ulg.load()
    out = ["# Element list", "",
           f"All {len(cat)} element ids of the catalog with geometry, names, aliases and description, "
           "grouped as in the data files. Pictures of every element: [catalog pages](../03-catalog.md).", ""]
    for group, els in by_group(cat).items():
        out += [f"## {group}", "", "| id | geometry | en | de | aliases | description |", "|---|---|---|---|---|---|"]
        for el in els:
            out.append(f"| `{el.id}` | {', '.join(el.geometry)} | {cell(el.name('en'))} | {cell(el.name('de'))} | "
                       f"{cell(', '.join(el.aliases))} | {cell(el.description.get('en', ''))} |")
        out.append("")
    write("element-list.md", "\n".join(out))


def attributes() -> None:
    cat = ulg.load()
    docs = cat.settings["attributes"]
    cols = [("sealing", "sealing"), ("bdla_class", "bdla"), ("bff", "BFF"), ("bff_1990", "BFF 1990"),
            ("runoff_cs", "Cs"), ("runoff_cm", "Cm"), ("albedo", "albedo"), ("emissivity", "ε"),
            ("nrr_urban_green", "NRR green"), ("canopy", "canopy"), ("layer", "layer")]
    out = ["# Element attributes", "",
           "Standard coefficients carried by each element. Empty cells mean *no published value*: "
           "`ulg.indicators()` reports them as coverage below 1 instead of guessing.", "",
           "## Sources", "", "| attribute | meaning | source | evidence |", "|---|---|---|---|"]
    for key, d in docs.items():
        values = d.get("values")
        if isinstance(values, dict):
            values = "; ".join(f"{k} = {v}" for k, v in values.items())
        elif values:
            values = ", ".join(values)
        meaning = " ".join(x for x in (d.get("meaning"), f"Values: {values}." if values else "") if x)
        out.append(f"| `{key}` | {cell(meaning)} | {cell(d.get('source', ''))} | {cell(d.get('evidence', '') or '')} |")
    out += ["", "Evidence: V = read in the primary source; S = secondary source (a published reproduction of "
            "the standard); house = UrbanSens convention, not a standard.", ""]

    def fmt(v):
        if v is None:
            return ""
        if v is True:
            return "yes"
        if v is False:
            return "no"
        return f"{v:g}" if isinstance(v, float) else str(v)

    for group, els in by_group(cat).items():
        rows = [el for el in els if any(k in el.attributes for k, _ in cols)]
        if not rows:
            continue
        out += [f"## {group}", "", "| id | " + " | ".join(h for _, h in cols) + " |", "|---" * (len(cols) + 1) + "|"]
        for el in rows:
            out.append(f"| `{el.id}` | " + " | ".join(fmt(el.attributes.get(k)) for k, _ in cols) + " |")
        out.append("")
    write("attributes.md", "\n".join(out))


def crosswalks() -> None:
    cat = ulg.load()
    cov = crosswalk.coverage(cat)
    out = ["# Crosswalks", "",
           "Every external classification the library can translate into element ids. "
           "Fit grades: **exact** (same class), **narrower** (the external class is a subset of the element), "
           "**broader** (the external class is wider than the element), **nearest** (closest drawable element), "
           "**none** (nothing to draw). File format: [crosswalk-format.md](crosswalk-format.md).", "",
           "| scheme | title | entries | elements | exact | narrower | broader | nearest | none | official colours |",
           "|---|---|---|---|---|---|---|---|---|---|"]
    for name, sch in sorted(crosswalk.schemes(cat).items()):
        c = cov[name]
        f = c["fits"]
        out.append(f"| `{name}` | {cell(sch.title)} | {c['entries']} | {c['elements']} | "
                   + " | ".join(str(f.get(k, 0)) for k in ("exact", "narrower", "broader", "nearest", "none"))
                   + f" | {len(sch.colors())} |")
    out.append("")
    for name, sch in sorted(crosswalk.schemes(cat).items()):
        out += [f"## `{name}` · {cell(sch.title)}", ""]
        if sch.publisher:
            out.append(f"- **Publisher:** {cell(sch.publisher)}")
        if sch.version:
            out.append(f"- **Version:** {cell(sch.version)}")
        if sch.source:
            out.append(f"- **Source:** {cell(sch.source)}")
        fields = sorted(set(sch._aliases) - {"code"})
        out.append(f"- **Key field:** `{sch.key}`" + (f"; also read: {', '.join(f'`{x}`' for x in fields)}" if fields else ""))
        if sch.hierarchy:
            out.append(f"- **Hierarchy fallback:** {sch.hierarchy}")
        lic = sch.data.get("license_note")
        if lic:
            out.append(f"- **Licence note:** {cell(lic)}")
        if sch.note:
            out += ["", cell(sch.note)]
        out.append("")
    write("crosswalks.md", "\n".join(out))


def themes() -> None:
    out = ["# Themes", "",
           "The same catalog drawn in other conventions: `ulg.render_svg(data, theme=...)`, "
           "`ulg export qgis DIR --theme ...`. Official themes use flat colours and exact lines.", "",
           "| theme | title | hand-drawn | textures | background |", "|---|---|---|---|---|"]
    for name in ulg.themes():
        t = ulg.load(name).theme
        out.append(f"| `{name}` | {cell(t.get('title', name))} | {t.get('handdrawn', 1.0)} | "
                   f"{t.get('textures', 'all')} | {t.get('background', 'paper.base')} |")
    out.append("")
    for name in ulg.themes():
        t = ulg.load(name).theme
        out += [f"## `{name}` · {cell(t.get('title', name))}", "", cell(t.get("description", "")), ""]
        if t.get("source"):
            out.append(f"- **Source:** {cell(t['source'])}")
        if t.get("evidence"):
            out.append(f"- **Evidence:** {cell(t['evidence'])}")
        out.append("")
    write("themes.md", "\n".join(out))


def _doc(obj, level: str = "###", name: str | None = None) -> list[str]:
    name = name or obj.__name__
    try:
        sig = str(inspect.signature(obj))
    except (TypeError, ValueError):
        sig = ""
    if inspect.isclass(obj):
        head = f"{level} class `{name}`"
    else:
        head = f"{level} `{name}`"
    text = inspect.getdoc(obj) or ""
    return [head, "", f"```python\n{name}{sig}\n```", "", text, ""]


def api() -> None:
    out = ["# API reference", "",
           "Generated from the docstrings. Guides with examples: [Python](../04-python.md), "
           "[GIS and web](../05-gis-and-web.md).", "", "## Package `ulg`", ""]
    for name in ulg.__all__:
        obj = getattr(ulg, name)
        if callable(obj):
            out += _doc(obj, name=f"ulg.{name}" if not inspect.isclass(obj) else name)
    sections = [
        ("Crosswalk helpers `ulg.crosswalk`", crosswalk, ["coverage", "validate"]),
        ("Legibility `ulg.check`", check, ["report", "format_report", "close_pairs", "mark_contrast", "land_cover"]),
        ("Demo data `ulg.datasets`", datasets, [n for n in ("demo_park", "demo_park_places", "demo_park_gdf") if hasattr(datasets, n)]),
        ("QGIS `ulg.export.qgis`", qgis, ["export_qgis", "layer_style", "style_library", "palette_gpl", "symbol_for",
                                         "strip_symbol", "width_expression"]),
        ("Web `ulg.export.web`", web, ["export_web", "to_geojson", "maplibre_layers", "maplibre_sprite", "pattern_files",
                                       "patterns_svg"]),
        ("OGC SLD `ulg.export.sld`", sld, ["export_sld", "sld"]),
        ("Design tokens `ulg.export.tokens`", tokens, ["css", "dtcg", "tokens_json", "catalog_json"]),
    ]
    for title, mod, names in sections:
        out += [f"## {title}", ""]
        for n in names:
            out += _doc(getattr(mod, n), name=f"{mod.__name__}.{n}")
    out += ["## Command line `ulg`", "", "Also available as `python -m ulg`.", ""]
    parser = cli.build_parser() if hasattr(cli, "build_parser") else None
    helps = []
    if parser is not None:
        helps.append(("ulg", parser.format_help()))
        sub = next(a for a in parser._actions if a.__class__.__name__ == "_SubParsersAction")
        for name, p in sub.choices.items():
            helps.append((f"ulg {name}", p.format_help()))
    else:
        buf = io.StringIO()
        with redirect_stdout(buf):
            try:
                cli.main(["--help"])
            except SystemExit:
                pass
        helps.append(("ulg", buf.getvalue()))
    for title, text in helps:
        out += [f"### `{title}`", "", "```text", text.rstrip(), "```", ""]
    write("api.md", "\n".join(out))


def main() -> None:
    for fn in (element_list, attributes, crosswalks, themes, api):
        fn()


if __name__ == "__main__":
    main()
